---
title: Ease of Access
description: The provided commands modify the Windows Registry to reset various accessibility settings, effectively disabling them.
actions:
  # HKCU
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\AudioDescription'}
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\Blind Access'}
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\HighContrast'}
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\Keyboard Preference'}
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\Keyboard Response'}
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\MouseKeys'}
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\On'}
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\ShowSounds'}
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\SlateLaunch'}
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\SoundSentry'}
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\StickyKeys'}
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\TimeOut'}
  - !registryKey: {path: 'HKCU\Control Panel\Accessibility\ToggleKeys'}
  # HKU
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\AudioDescription'}
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\Blind Access'}
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\HighContrast'}
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\Keyboard Preference'}
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\Keyboard Response'}
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\MouseKeys'}
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\On'}
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\ShowSounds'}
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\SlateLaunch'}
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\SoundSentry'}
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\StickyKeys'}
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\TimeOut'}
  - !registryKey: {path: 'HKU\.DEFAULT\Control Panel\Accessibility\ToggleKeys'}
  # HKCU
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\AudioDescription', value: 'Flags', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\Blind Access', value: 'Flags', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\HighContrast', value: 'Flags', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\Keyboard Preference', value: 'Flags', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\Keyboard Response', value: 'Flags', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\MouseKeys', value: 'Flags', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\On', value: 'Flags', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\ShowSounds', value: 'Flags', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\SlateLaunch', value: 'Flags', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\SoundSentry', value: 'Flags', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\StickyKeys', value: 'Flags', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\TimeOut', value: 'Flags', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKCU\Control Panel\Accessibility\ToggleKeys', value: 'Flags', type: REG_SZ, data: '0'}

