---
title: MaxFreeTcbs
description: >
  The "MaxFreeTcbs" parameter specifies the maximum amount of memory, in bytes, that can be used for storing Transport Control Blocks (TCBs).
  TCBs are essential data structures used by the TCP/IP network protocol to manage active network connections.
actions:
  # Change MaxFreeTcbs to 65536 bytes (default - varies with the system and amount of physical memory on the computer)
  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters'
      value: 'MaxFreeTcbs'
      type: REG_DWORD
      data: '65536'