---
title: MaxUserPort
description: >
  The "MaxUserPort" parameter specifies the highest network port number that can be used by a Windows system for outgoing connections.
actions:
  # Change MaxUserPort to 65534 bytes (default - 5000 bytes)
  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters'
      value: 'MaxUserPort'
      type: REG_DWORD
      data: '65534'