---
title: IRPStackSize
description: >
  The "IRPStackSize" parameter defines the size of the Input/Output Request Packet (IRP) stack in kernel memory.
  IRPs are essential data structures used by Windows to communicate between various layers of the operating system, including device drivers and the kernel.
actions:
  # Change IRPStackSize to 32 IRPs (default - 15 IRPs)
  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters'
      value: 'IRPStackSize'
      type: REG_DWORD
      data: '32'