---
title: DirectX Graphics Kernel
description: >
  DXGKrnl primarily deal with the synchronization and management of graphics resources between different components of the system.
actions:
   # This configuration sets various registry values under the DirectX Graphics Kernel (DXGKrnl) service to enable and fine-tune graphics resource management and synchronization features.
   # These settings include enabling GPU-based GDI operations, supporting CDD and DWM interoperation, managing swap chains, handling vertical blank events for synchronization,
   # and adjusting latency tolerances. These changes aim to improve graphics performance, resource handling, and system stability.

  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'CreateGdiPrimaryOnSlaveGPU', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'DriverSupportsCddDwmInterop', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'DxgkCddSyncDxAccess', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'DxgkCddSyncGPUAccess', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'DxgkCddWaitForVerticalBlankEvent', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'DxgkCreateSwapChain', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'DxgkFreeGpuVirtualAddress', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'DxgkOpenSwapChain', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'DxgkShareSwapChainObject', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'DxgkWaitForVerticalBlankEvent', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'DxgkWaitForVerticalBlankEvent2', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'SwapChainBackBuffer', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'TdrResetFromTimeoutAsync', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'MonitorLatencyTolerance', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl', value: 'MonitorRefreshLatencyTolerance', type: REG_DWORD, data: '0'}
