---
title: System Boot Configuration
description: >
  These commands modify various system boot settings, including startup delay, boot execution sequence,
  and BCD settings for system integrity, memory management, and debug mode.
privilege: TrustedInstaller
actions:
  - !writeStatus: {status: 'Configuring boot settings'}
  # Set startup delay for applications to 0 milliseconds
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Serialize', value: 'StartupDelayInMSec', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Serialize', value: 'WaitforIdleState', type: REG_DWORD, data: '0'}

  # Configure automatic file system check on C: drive at boot
  - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\Session Manager', value: 'BootExecute', type: REG_MULTI_SZ, data: 'autocheck autochk /k:C*'}

  ## HPET Disable(0.1 to 0.15ms delay with HPET on while turning it off can gain you around 3-4 FPS)
  # -------------------------------------------------------------------------------#

  # Disable platform clock
  - !run: {exe: 'bcdedit', args: '/set useplatformclock false', showOutput: false}

  # Disable dynamic ticks
  - !run: {exe: 'bcdedit', args: '/set disabledynamictick yes', showOutput: false}

  # -------------------------------------------------------------------------------#
 
  # Use classic boot menu style
  - !run: {exe: 'bcdedit', args: '/set bootmenupolicy Legacy', showOutput: false}

  # Disable isolated context for drivers
  - !run: {exe: 'bcdedit', args: '/set isolatedcontext no', showOutput: false}

  # Disable debugging
  - !run: {exe: 'bcdedit', args: '/set debug no', showOutput: false}

  # Disable integrity services
  - !run: {exe: 'bcdedit', args: '/set integrityservices disable', showOutput: false}

  # Disable Emergency Management Services (EMS)
  - !run: {exe: 'bcdedit', args: '/set ems no', showOutput: false}

  # Disable Physical Address Extension (PAE)
  - !run: {exe: 'bcdedit', args: '/set pae ForceDisable', showOutput: false}

  # Disable Linear Address 57 feature
  - !run: {exe: 'bcdedit', args: '/set linearaddress57 OptOut', showOutput: false}

  # Increase user-mode address space to 256MB
  - !run: {exe: 'bcdedit', args: '/set increaseuserva 268435328', showOutput: false}

  # Use all of the first megabyte of memory
  - !run: {exe: 'bcdedit', args: '/set firstmegabytepolicy UseAll', showOutput: false}

  # Set low memory threshold to 128MB
  - !run: {exe: 'bcdedit', args: '/set avoidlowmemory 0x8000000', showOutput: false}

  # Disable low memory usage
  - !run: {exe: 'bcdedit', args: '/set nolowmem yes', showOutput: false}

  # Disable in-memory settings
  - !run: {exe: 'bcdedit', args: '/set allowedinmemorysettings 0x0', showOutput: false}

  # Set boot menu timeout to 15 seconds
  - !run: {exe: 'bcdedit', args: '/timeout 15', showOutput: false}
