---
title: Microsoft Store Configuration
description: >
  The provided registry settings configure various aspects related to Microsoft Store and system services.
  These settings control Microsoft Store behavior, disable certain upgrades, disable updates and manage error reporting.
  Additionally, they ensure essential system services are enabled for the proper functioning of the firewall,
  which is crucial for Microsoft Store functionality.
actions:
  # Disable Auto-Update for Microsoft Store
  # - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\WindowsStore', value: 'AutoDownload', type: REG_DWORD, data: '4'}
  # - !registryValue: {path: 'HKCU\Software\Policies\Microsoft\WindowsStore', value: 'DisableOSUpgrade', type: REG_DWORD, data: '1'}
  # - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\WindowsStore', value: 'DisableOSUpgrade', type: REG_DWORD, data: '1'}

  # Configure Services for Proper Microsoft Store Functionality
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\WinHttpAutoProxySvc', value: 'Start', type: REG_DWORD, data: '2'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\LicenseManager', value: 'Start', type: REG_DWORD, data: '2'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\InstallService', value: 'Start', type: REG_DWORD, data: '2'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\ClipSVC', value: 'Start', type: REG_DWORD, data: '2'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\wscsvc', value: 'Start', type: REG_DWORD, data: '2'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\mpssvc', value: 'Start', type: REG_DWORD, data: '2'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\BITS', value: 'Start', type: REG_DWORD, data: '2'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\BFE', value: 'Start', type: REG_DWORD, data: '2'}

  # Additional Registry parameters for Microsoft Store
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Registration Wizard Control', value: 'NoRegistration', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\HandwritingErrorReports', value: 'PreventHandwritingErrorReports', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\TabletPC', value: 'PreventHandwritingDataSharing', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\SearchCompanion', value: 'DisableContentFileUpdates', type: REG_DWORD, data: '1'}