---
title: File System
description: >
  This script modifies various file system behaviors using the fsutil command in Windows.
privilege: TrustedInstaller
actions:
  # Enables TRIM support for SSDs to optimize their performance and lifespan
  # - !run: {exe: 'fsutil', args: 'behavior set disabledeletenotify 0', showOutput: false} # Added in MultiTool.ps1 in SSD Configuration function

  # Disables automatic NTFS file compression to avoid using system resources for compression
  - !run: {exe: 'fsutil', args: 'behavior set disablecompression 1', showOutput: false}

  # Disables encryption of the paging file used for virtual memory, which might be done for performance reasons
  - !run: {exe: 'fsutil', args: 'behavior set encryptpagingfile 0', showOutput: false}

  # Turns off updating the last access timestamp for files to potentially improve file system performance
  - !run: {exe: 'fsutil', args: 'behavior set disablelastaccess 1', showOutput: false}

  # Sets the interval (in seconds) for notifications about disk quota usage; 5400 seconds equals 1.5 hours
  - !run: {exe: 'fsutil', args: 'behavior set quotanotify 5400', showOutput: false}

  # Disables the creation of 8.3 format filenames for compatibility with older applications, which can improve file system performance
  - !run: {exe: 'fsutil', args: 'behavior set disable8dot3 1', showOutput: false}


