---
title: Disable MPO
description: >
  MPO in Windows enhances video playback performance and quality but can cause issues like visual artifacts,
  sync problems with G-Sync/FreeSync, and HDR conflicts. Currently, it's recommended to disable MPO to avoid these problems.
actions:
  - !registryValue: 
      path: 'HKLM\SOFTWARE\Microsoft\Windows\Dwm'
      value: 'OverlayTestMode'
      type: REG_DWORD
      data: '5'