---
title: Optimized Browsers & Essential Components installation
description: >
  This section includes commands for installing popular web browsers (Edge, Brave, Firefox, Chrome) and optimizing them by disabling telemetry, updates, and unnecessary services. 
  It also installs essential components (.NET 3.5, DirectX, VCRedist) and adds browser extensions (uBlockOrigin).
actions:
  # Installing Chocolatey
  - !powerShell:
      command: 'Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString(''https://community.chocolatey.org/install.ps1''))'
      weight: 30

  - !writeStatus: {status: 'Tweaking Edge', option: '!remove-msedge'}
  # Tweaking Edge
  - !taskKill: {name: 'MicrosoftEdgeUpdate', option: '!remove-msedge'}
  - !service: {name: 'edgeupdate', operation: change, startup: 4, option: '!remove-msedge'}
  - !service: {name: 'edgeupdatem', operation: change, startup: 4, option: '!remove-msedge'}
  - !service: {name: 'MicrosoftEdgeElevationService', operation: change, startup: 4, option: '!remove-msedge'}
  - !file: {path: 'C:\Program Files (x86)\Microsoft\EdgeUpdate', option: '!remove-msedge'}
  - !powerShell:
      command: '.\MultiTool.ps1 -MyArgument optimize_msedge'
      exeDir: true
      option: '!remove-msedge'
      weight: 300
  
  # Installing Brave
  - !writeStatus: {status: 'Installing Brave', option: 'browser-brave'}
  - !cmd:
      command: '"%ProgramData%\chocolatey\bin\choco.exe" install -y --force --allow-empty-checksums brave'
      weight: 100
      option: 'browser-brave'
  # Tweaking Brave
  - !taskKill: {name: 'BraveUpdate', option: 'browser-brave'}
  - !service: {name: 'brave', operation: change, startup: 4, option: 'browser-brave'}
  - !service: {name: 'bravem', operation: change, startup: 4, option: 'browser-brave'}
  - !service: {name: 'BraveElevationService', operation: change, startup: 4, option: 'browser-brave'}
  - !registryValue: {path: 'HKLM\SOFTWARE\BraveSoftware\Brave-Browser', value: 'ExtensionInstallForcelistEnabled', type: REG_DWORD, data: '1', option: 'browser-brave'}
  - !registryValue: {path: 'HKLM\SOFTWARE\BraveSoftware\Brave-Browser\ExtensionInstallForcelist', value: '1', type: REG_SZ, data: 'cjpalhdlnbpafiamejdnhcphjbkeiagm;https://clients2.google.com/service/update2/crx', option: 'browser-brave'}

  # Installing Firefox
  - !writeStatus: {status: 'Installing Firefox', option: 'browser-firefox'}
  - !cmd:
      command: '"%ProgramData%\chocolatey\bin\choco.exe" install -y --force --allow-empty-checksums firefox'
      weight: 100
      option: 'browser-firefox'
  # Tweaking Firefox
  - !taskKill: {name: 'Firefox', option: 'browser-firefox'}
  # - !powerShell:
  #     command: '.\Firefox-Tweaks.ps1'
  #     exeDir: true
  #     option: 'browser-firefox'
  #     weight: 100
  - !service: {name: 'MozillaMaintenance', operation: change, startup: 4, option: 'browser-firefox'}

  # Installing Chrome
  - !writeStatus: {status: 'Installing Chrome', option: 'browser-chrome'}
  - !cmd:
      command: '"%ProgramData%\chocolatey\bin\choco.exe" install -y --force --allow-empty-checksums googlechrome'
      weight: 100
      option: 'browser-chrome'
  # Tweaking Chrome
  - !taskKill: {name: 'GoogleUpdate', option: 'browser-chrome'}
  - !taskKill: {name: 'GoogleUpdateOnDemand', option: 'browser-chrome'}
  - !service: {name: 'googlechromeelevationservice', operation: change, startup: 4, option: 'browser-chrome'}
  - !service: {name: 'gupdatem', operation: change, startup: 4, option: 'browser-chrome'}
  - !service: {name: 'gupdate', operation: change, startup: 4, option: 'browser-chrome'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\DisallowRun', value: '1', type: REG_SZ, data: 'software_reporter_tool.exe', option: 'browser-chrome'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Google\Chrome\Recommended', value: 'MetricsReportingEnabled', type: REG_DWORD, data: '0', option: 'browser-chrome'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Google\Chrome\Recommended', value: 'DeviceMetricsReportingEnabled', type: REG_DWORD, data: '0', option: 'browser-chrome'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Google\Chrome', value: 'ChromeCleanupEnabled', type: REG_DWORD, data: '0', option: 'browser-chrome'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Google\Chrome', value: 'DefaultPopupsSetting', type: REG_DWORD, data: '0', option: 'browser-chrome'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Google\Chrome', value: 'DefaultSensorsSetting', type: REG_DWORD, data: '0', option: 'browser-chrome'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Google\Chrome', value: 'UserFeedbackAllowed', type: REG_DWORD, data: '0', option: 'browser-chrome'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Google\Chrome', value: 'SpellCheckServiceEnabled', type: REG_DWORD, data: '0', option: 'browser-chrome'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Google\Chrome', value: 'SpellcheckEnabled', type: REG_DWORD, data: '0', option: 'browser-chrome'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Google\Chrome', value: 'HomepageIsNewTabPage', type: REG_DWORD, data: '0', option: 'browser-chrome'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Google\Chrome', value: 'BackgroundModeEnabled', type: REG_DWORD, data: '0', option: 'browser-chrome'}
  - !cmd:
      command: '"%ProgramData%\chocolatey\bin\choco.exe" install -y --force --allow-empty-checksums ublockorigin-chrome'
      weight: 10
      option: 'browser-chrome'

  # Installing .NET 3.5
  - !writeStatus: {status: 'Installing .NET 3.5', option: 'dotnet'}
  - !cmd:
      command: '"%ProgramData%\chocolatey\bin\choco.exe" install -y --force --allow-empty-checksums dotnet3.5'
      weight: 70
      option: 'dotnet'

  # Installing DirectX
  - !writeStatus: {status: 'Installing DirectX', option: 'directx'}
  - !cmd:
      command: '"%ProgramData%\chocolatey\bin\choco.exe" install -y --force --allow-empty-checksums directx'
      weight: 100
      option: 'directx'

  # Installing VCRedist
  - !writeStatus: {status: 'Installing VCRedist', option: 'vcredist'}
  - !cmd:
      command: '"%ProgramData%\chocolatey\bin\choco.exe" install -y --force --allow-empty-checksums vcredist-all'
      weight: 150
      option: 'vcredist'